application: bs-udacity-cs253
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /images
  static_dir: images
  expiration: "99d"

- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /
  script: login.app
# - url: /blog/login
  # script: login.app
- url: /homework
  script: main.app

- url: /course_work
  script: main.app

- url: /unit1/helloudacity
  script: main.app

- url: /course_work/unit2/birthday
  script: birthday.app

- url: /course_work/unit3/ASCIIChan
  script: aschii.app

- url: /unit2/rot13
  script: ROT13.app

- url: /homework/unit2/signup
  script: signup.app

- url: /unit2/welcome
  script: signup.app

- url: /blog/?
  script: blog.app

- url: /blog/newpost
  script: blog.app

- url: /blog/([0-9]+)
  script: blog.app

- url: /course_work/unit4/pagecounter
  script: pagecounter.app

- url: /unit4/signup
  script: register.app# - url: /blog/signup
  # script: register.app

- url: /unit4/welcome
  script: register.app
# - url: /blog/welcome
  # script: register.app
- url: /unit4/logout
  script: logout.app# - url: /blog/logout
  # script: logout.app  
- url: /blog.json
  script: blog.app

# - url: /blog/.json
  # script: blog.app  
- url: /blog/([0-9]+).json
  script: blog.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
